---
onepam_server_url: "https://onepam.com"
onepam_tenant_id: ""
onepam_group_uuid: ""
onepam_agent_version: "latest"
onepam_log_level: "info"
onepam_release_url: "https://updates.onepam.com"
onepam_install_dir: "/opt/onepam"
